### ISSUE TITLE
Solarized Theme

### ISSUE THREAD

**Issue by anishmittal2020** [rignaneseleo/SlimSocial-for-Facebook#107]
Please provide Solarized theme as its easier on eyes.

**Comment by rignaneseleo** [comment]
I would need the CSS code for that.

**Comment by anishmittal2020** [comment]
@rignaneseleo  [This is a link to CSS for Facebook for dark theme | Userstyles.org](https://userstyles.org/styles/136318/clear-dark-facebook-by-book777).

If you could provide an option for the user to upload their CSS in the app it will be good then we can upload any theme as the user likes.

**Comment by rignaneseleo** [comment]
I tried it on touch.facebook.com and it doesn't work. Have you tried?

**Comment by anishmittal2020** [comment]
Hello! I tried on touch.facebook.com, using Firefox 84, using Stylus Extension. And I installed the theme on my browser using Install button located at  [sars-fansubs.com - cleaner | Userstyles.org](https://userstyles.org/styles/136318/clear-dark-facebook-by-book777). It worked for me.

I was hoping that in your app you could provide an option where users could upload whatever themes they like. Certain themes can also me made available as presets.

**Comment by rignaneseleo** [comment]
Sorry but I tried it again on Firefox removing the first and last line to make it work and it doesn't seem something ready for production: some text is not readable and some parts are not colored. You should review it and open a new thread. Thanks!
