### ISSUE TITLE
Request for implementing forward and back browsing

### ISSUE THREAD

**Issue by barbaMimmo** [rignaneseleo/SlimSocial-for-Facebook#108]
When browsing Facebook from the "m" and the "mbasic" website, as like as with the "touch" version, from a web browser you can always go back and forth, and this proves useful in many situations. In SSF, instead, it doesn't seem to be possible.
Please, take into consideration implementing these commands in the next release.

**Comment by rignaneseleo** [comment]
Maybe in the next release!
Stay tuned.
