### ISSUE TITLE
Folder for downloaded content, and name of downloaded picture files

### ISSUE THREAD

**Issue by barbaMimmo** [rignaneseleo/SlimSocial-for-Facebook#109]
There is an issue with the way SSF creates its download folder in old Android devices (where SSF comes expecially useful) like those running KitKat 4.4.4 and lower: it creates a whole subfolder structure "storage/emulated/0/download" (and another sub of it, called "SlimSocial", if you chose so in app settings) in the "storage/emulated/0/" system folder, whilst it should use the already existing default "download" folder. This way, the whole path becomes: "storage/emulated/0/storage/emulated/0/download/slimsocial" which is clearly a bug.
As a comparison, on the very same devices this simple app uses the Android default "download" folder correctly for creating its "imcktg" subfolder where to put new files:
https://github.com/achromaticmetaphor/IMCKTG
Please consider correcting this behaviour. Thanks really for your precious work!

**Comment by barbaMimmo** [comment]
As for the part regarding renaming of downloaded files, sorry, it got truncated from the previous text.
Here it follows.
SSF renames each and every downloaded file, something like "SlimSocial-1,jpg", or "SlimSocial Download" instead of preserving the unique original name of the file from the Facebook servers. This behaviour causes problems when you move those files to a custom folder for backup: each time its folder is empty, SSF start the count from zero again, so the next time you move files you will have a lot of identical names, without any unicity. Moreover, if you already downloaded a picture, and by chance choose to download it again, it would be re-downloaded (with a new number and the same basic name "SlimSocial-n.jpg" in old Android devices running KitKat and lower, while it will have many times the exact same name "SlimSocial Download" without numbers added, e.g. in Nougat) without allowing you to notice the fact the file already existed in your download folders.
I found this behaviour quite annoying and unuseful. Why couldn't SSF simply keep the actual and original filename, like for example Firefox does when you download anything from m.facebook.com ?

**Comment by rignaneseleo** [comment]
Original names are really long that do not sort by chronological date. In most of the cases, renaming is a good approach.
