### ISSUE TITLE
Messaging functionnality just broke

### ISSUE THREAD

**Issue by voxitme** [rignaneseleo/SlimSocial-for-Facebook#110]
When trying to access messages using this button:
![2020_12_12_120724_1](https://user-images.githubusercontent.com/36687040/101963143-459c1e00-3c0e-11eb-828a-dd0b003baeaa.png)

This is returned:
"The link you followed may be broken, or the page has been deleted."
![Screenshot_20201212-000935_SlimSocial_for_Facebook_1](https://user-images.githubusercontent.com/36687040/101963194-6795a080-3c0e-11eb-9252-975f90e64897.png)

Change in the API?

**Comment by Ansem93** [comment]
same issue here :( messenger.com still works, but not touch.facebook

**Comment by petyy** [comment]
I have the same issue now :-(

**Comment by eritos61** [comment]
Same here!! This issue appeared after the break down of fb amd messenger a couple of days ago!! The same issue had happenes in the past, perhaps a year or so agoa, again after a fb collapse. It also returned on its own.

**Comment by eritos61** [comment]
Is there sth we could do as users, to rectify the problem???

**Comment by voxitme** [comment]
OK, sorry I'm going to close this issue because it's actually not related to SlimSocial...!
