### ISSUE TITLE
Messaging functionnality not working

### ISSUE THREAD

**Issue by eritos61** [rignaneseleo/SlimSocial-for-Facebook#111]
Since fb collapse, a couple of days ago, the message button when pressed, has no functionality. 

I am borrowing the image from a fellow user:

![1](https://user-images.githubusercontent.com/75907291/102004447-6604cf00-3d19-11eb-82a8-16e0c908a718.png)

![2](https://user-images.githubusercontent.com/75907291/102004451-75841800-3d19-11eb-8751-36201723b266.png)

Any ideas as to what is happening??  Even as I write this, no access to messages is possible!!

**Comment by K-Ray** [comment]
slimsocial gets data from m.facebook.com/messages that pages has been removed. possibly to do with planned merge of messenger and chat from instagram

**Comment by eritos61** [comment]
K-Ray thank you for replying!! Any ideas/thoughts as to when/if this issue will be handled by Slimsocial? For, as far as I can see, there is nothing a user can do to rectify the problem......

**Comment by K-Ray** [comment]
Sorry, I'm just a user of the app and noticed the same problem and came looking for an update.

**Comment by eritos61** [comment]
K-Ray thank you for replying!!  Lets hope we are not the only ones facing this issue!!!!

**Comment by voxitme** [comment]
@eritos61 I closed my similar issue because it seems to have nothing to do with SlimSocial, at least as long as m.facebook.com is facing the exact same issue...

**Comment by voxitme** [comment]
@eritos61 I closed my similar issue (the one your are taking the screenshots from) because it seems to have nothing to do with SlimSocial, at least as long as m.facebook.com is facing the exact same issue...

**Comment by eritos61** [comment]
@voxtime Thank you for your input to my novice inquiry, regarding the malfunction of messaging via signal in Fb. As you may have noticed, in my opening lines, i state "I am borrowing the image from a fellow user:" (this as a reply to your previous comment). 

Furthermore, I would like to add for the rest of novice users, like myself, a link that I recently came across, that explains what has happened, on the FB side, and what is still happening, as far as messaging and other functionalities of FB are concerned. 

https://mspoweruser.com/facebook-messenger-says-some-features-not-available-heres-why/

@voxtime the above link, supports your statement that the malfunction is not Signal related.  

However, the statement on its own, albeit correct at its core, was not explanatory enough for my entry level expertise on developer issues, hence this effort here, to pursue a logical explanation. (that i believe the article in the above link provides).

Merry Xmas to all, and keep covid safe.

**Comment by rignaneseleo** [comment]
Hey guys, SlimSocial 4.0.0 is coming with a fix for messages! 

I added the support to messenger.com by pressing the messages button in the topbar.

Enjoy!

**Comment by bezda** [comment]
@rignaneseleo That;s great news, thank you. Would you have a release date for the new version?

**Comment by rignaneseleo** [comment]
v5.0.0 is now in BETA, go check it out!

**Comment by schwim0341** [comment]
where can you get the apk of 5.0?

**Comment by rignaneseleo** [comment]
from play store, scroll down to subscribe as beta tester and then download the app
