### ISSUE TITLE
Unable to scroll up the menu page after scrolling down, the page refreshes instead (re-report)

### ISSUE THREAD

**Issue by rredford** [rignaneseleo/SlimSocial-for-Facebook#112]
Expected behavior

I expect i'll be able to scroll down and then back up the menu page without experiencing any hitch.
Actual behavior

I am unable to scroll back up after scrolling down. Instead, when i try to scroll up, the page tries to refresh itself. It likes my thumb motions are directed at scrolling up, while the page seems bent on refreshing.
How to reproduce

    download the app from fdroid store
    launch app and allow permissions if prompted
    Turn on data connections
    Login with your facebook details
    Refresh the homepage
    Click on the three slashes just below the three dots at the top right corner.
    Attempt scrolling down
    Now try scrolling back up, you'll notice the page refreshes instead

**Comment by rignaneseleo** [comment]
Hi, thanks for reporting.

What version of the app are you using?

**Comment by rredford** [comment]
5.0.3
