### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [rignaneseleo/SlimSocial-for-Facebook#115]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by rignaneseleo** [comment]
Hi, thanks for the suggestion.

I have no time to spend on this right now, but I uploaded all the new screenshot [here](https://github.com/rignaneseleo/SlimSocial-for-Facebook/tree/master/img/store) in case you or someone else wants to do the job :)
