### ISSUE TITLE
Messenger: very slow to load (5.0.0)

### ISSUE THREAD

**Issue by lsorba** [rignaneseleo/SlimSocial-for-Facebook#117]
First of all, thank you for your awesome work! 

I am using the version 5.0.0 and have troubles displaying the messenger, it works but needs a long time to be displayed.
Would there be a way to display it faster? 
I would love to uninstall the messenger definitely! 

Thanks

OS: Android 10
Device: OnePlus 6
App version 5.0.0

**Comment by rignaneseleo** [comment]
Hi, you are right. Messenger is slow to load and this is because it is heavy.
At the moment it is the only solution since the light one has been removed from facebook.

I am now looking for solutions, stay tuned!
