### ISSUE TITLE
Messenger: Unable to send a message to a new contact

### ISSUE THREAD

**Issue by Ja-Peter** [rignaneseleo/SlimSocial-for-Facebook#118]
Hello,
I started to use your app just recently and I like its simplicity!

However, I miss one essential Messenger feature: A button to create a new message with a 'To:' search box.
Currently, there is no way to send a message to a new contact (or to someone to whom I have not sent any message yet).

Thanks!
Peter

**Comment by NestaYor** [comment]
app was updated here 10 days ago and this is still a problem....add to the fact that, even though it seems to be updated on the hub, there hasent been a push to fdroid since June 2020. I wouldn't hold your breathe and suggest you look into alternative apps.
