### ISSUE TITLE
Messenger: Dark mode

### ISSUE THREAD

**Issue by amine250** [rignaneseleo/SlimSocial-for-Facebook#119]
Hello,

Following the breaking changes Facebook made to its messenger API, the only FOSS app I found that wraps messenger.com is this one and I'm really grateful.

However, the dark mode setting gets applied only on the news feed and not the messenger tab, is it possible to implement this?

Thanks!

**Comment by georgettica** [comment]
Fyi, there are two ways to open the messenger tab,one it one the top row and the other is a line under it.

If you click the bottom one the dark theme is still applied (works on my device)

Hope that helps!

**Comment by linje12** [comment]
Now when trying to open it the other way, it just gives error:  You can access your messages through a desktop browser, or by downloading Messenger in the app store.
