### ISSUE TITLE
Remove tracking mode fbclid

### ISSUE THREAD

**Issue by rzafiamy** [rignaneseleo/SlimSocial-for-Facebook#120]
Everytimes we click on link shared in facebook they add a tracking mode ( e.g.  : https://link-shared-with-fb/fbclid=xxxxxxxxxxxxxxxxxx) 
Is it possible to remove them before opening the url in browser ?

**Comment by Mennaruuk** [comment]
Yes, is there a way this can be averted?

**Comment by rignaneseleo** [comment]
Is it used only to track the users or also to get you to the right place?

**Comment by miiichael** [comment]
My understanding is that the FB CLick ID parameter is used only for tracking purposes.
