### ISSUE TITLE
"Unsupported browser" notice

### ISSUE THREAD

**Issue by ghost** [rignaneseleo/SlimSocial-for-Facebook#121]
The notice in the homepage says: 
"You're using a browser that isn't supported by Facebook, so we've redirected you to a simpler version to give you the best experience."

I installed the latest version of Webview.

The notice does not appear in LineageOS default browser, which uses webview.

**Comment by SingingTurnip** [comment]
I also get this using Samsung S10. I really wanted to ditch FB for this app too.

**Comment by rignaneseleo** [comment]
Hi guys, I'm investigating this. Apparently, it is not shown in every country.
