### ISSUE TITLE
Facebook pages do not open

### ISSUE THREAD

**Issue by ghomem** [rignaneseleo/SlimSocial-for-Facebook#123]
Whereas browsing the timeline and personal profiles works, currently the opening of facebook pages (different from personal profiles) does not work. When trying to browser a facebook page - either from tapping on the title via timeline or by finding the page via search - we get the error:

"No Internet Connection"
"Try again"

The Internet works fine on this phone, so this is probably just a misleading error message.

Thank you for your efforts on this app! :-)

![WhatsApp Image 2021-03-24 at 10 31 41](https://user-images.githubusercontent.com/3352900/112295888-43754100-8c8c-11eb-8c08-30642ee3d545.jpeg)

**Comment by Maarttt** [comment]
I also have this issue. Furthermore, I also cannot access pages linked to my own account. 

![Screenshot_20210405-190049_SlimSocial for Facebook](https://user-images.githubusercontent.com/81959288/113559699-2f92ed00-9645-11eb-94ad-faecd8143a6b.jpg)

**Comment by rignaneseleo** [comment]
Hi guys, I'm investigating this. Apparently, it is not shown in every country.

**Comment by Maarttt** [comment]
Thanks, Leo.

Today there was something different. I searched for a group and then, when
I clicked on the search result, it just took me back to the
homepage/newsfeed.

**Comment by ghomem** [comment]
Thanks for the effort @rignaneseleo . This is a very friendly app :-) Just to comment that the same result remains on my side (retested now).

**Comment by veritas44** [comment]
Videos on Watch link have the same error

**Comment by gsantner** [comment]
same here

**Comment by essamadel** [comment]
Having the same issue "No Internet Connection, Try again". Any solution so far? I like the app and I want to get over this issue.

**Comment by rignaneseleo** [comment]
Version 5.0.5 should fix this. Let me know ;)

**Comment by ghomem** [comment]
Awesome! Will retest as soon as it hits F-Droid.

**Comment by ghomem** [comment]
Hi @rignaneseleo , the app didn't hit the stores yet so I tested the apk directly. I can confirm that this problem is fixed :-). Super big thank you. I will send some support via the app.

**Comment by essamadel** [comment]
Hi @rignaneseleo, I have also tested the apk. I can also confirm that the issue has been resolved. Your efforts are much appreciated.

**Comment by ghomem** [comment]
Opened a separate issue for the videos:

https://github.com/rignaneseleo/SlimSocial-for-Facebook/issues/133

**Comment by rignaneseleo** [comment]
Thanks guys for the support. 
I'm having troubles with the PlayStore because of a security problem with the webview.
