### ISSUE TITLE
Viewing my page, not personal page but company's 

### ISSUE THREAD

**Issue by tidyboythfc** [rignaneseleo/SlimSocial-for-Facebook#128]
Everytime I try to post or view my business page it jist keeps saying "No Internet,  Try again" over and over. It works fine everywhere else but here. Is there an issue? I just cant post anything or view my page

**Comment by rignaneseleo** [comment]
Version 5.0.5 should fix this. Let me know ;)

**Comment by tidyboythfc** [comment]
Thanks,  on the store though there is only version 5.0.4 , I've redownloaded 5.0.4 to see if it updates. I'll let you know if any changesIs there a store where I've I can get 5.0.5? As I want to stop using everything facrbook official Thanks. If not ill give 5.0.4 a chance as it said it was released a month ago. Thanks for the reply. Mr M.On 09/06/2021, 14:13 Leo ***@***.***> wrote:

   
  Version 5.0.5 should fix this. Let me know ;)

**Comment by tidyboythfc** [comment]
Just found 5.0.5 on github as f droid and play didn't have it. Hope it works. Thanks Mr M.On 09/06/2021, 14:13 Leo ***@***.***> wrote:

   
  Version 5.0.5 should fix this. Let me know ;)

**Comment by tidyboythfc** [comment]
Sorry one more thing, the message isn't built im anymore, any plans to do so? As I don't want to have two apps and an official Facebook app on my phone haha Mr M.On 09/06/2021, 14:13 Leo ***@***.***> wrote:

   
  Version 5.0.5 should fix this. Let me know ;)

**Comment by rignaneseleo** [comment]
You can download v5.0.5 from here: https://github.com/rignaneseleo/SlimSocial-for-Facebook/releases/download/v5.0.5/SlimSocial_5.0.5.apk

On playstore they rejected it because of a compatibility problem (I'm working on that).

**Comment by tidyboythfc** [comment]
Thanks mate. Does that have a messenger built in like the good old days. Facebook have really gone to war with 3rd party better apps haven't they! I've got 5.0.5 from gitbub but it doesn't have the messages in it. Does this version to the link you have given me have them? Or is it just the github version of 5.0.5? Please let me know. Thanks Mr M.

 
  
  
 
 On 10/06/2021, 11:18 Leo ***@***.***> wrote:

   
  You can download v5.0.5 from here: https://github.com/rignaneseleo/SlimSocial-for-Facebook/releases/download/v5.0.5/SlimSocial_5.0.5.apk 
  On playstore they rejected it because of a compatibility problem (I'm working on that).

**Comment by rignaneseleo** [comment]
Hey guys, version 5.0.7 is in BETA on the playstore. Can you download and test it?

**Comment by tidyboythfc** [comment]
Hi there, I got it from play beta and the chat works nicely, but old issue's have come back. Like I now cannot post on my business page or load it, the previous version worked but the ones before didn't. Also I done a simple search and it just comes up with the same screen as when I try to get on my non personal page. I'll enclose screenshot of what I get. Well done for trying. Shame facebook now wants all your details too lile the proper app. Which is kind of annoying but I hear they are doing it to everyone. Here is the page I get when I search and try and get on my business page attached. MojoOn 16/06/2021, 11:05 Leo ***@***.***> wrote:

   
  Hey guys, version 5.0.7 is in BETA on the playstore. Can you download and test it?
