### ISSUE TITLE
Messenger not available in 5.0.5

### ISSUE THREAD

**Issue by g0bar** [rignaneseleo/SlimSocial-for-Facebook#132]
messenger doesn't load in new update

**Comment by ghomem** [comment]
Confirmed. It is redirecting to a screen that prompts for installation of the app.

**Comment by postapczuk** [comment]
I would suggest to check the KaiOS Facebook webapp, as the facebook chat works there like a charm. Moreover KaiOS is officialy supported, so probably the solution will work for longer period of time.

**Comment by g0bar** [comment]
> I would suggest to check the KaiOS Facebook webapp, as the facebook chat works there like a charm. Moreover KaiOS is officialy supported, so probably the solution will work for longer period of time.

Slimsocial is for android, is that one available as an apk?

**Comment by postapczuk** [comment]
> > I would suggest to check the KaiOS Facebook webapp, as the facebook chat works there like a charm. Moreover KaiOS is officialy supported, so probably the solution will work for longer period of time.
> 
> Slimsocial is for android, is that one available as an apk?

of course slimsocial ia for android not for KaiOS. I've just suggested for it's developer on what code he could base his solution to make it work for longer time.

**Comment by rignaneseleo** [comment]
Possibly fixed in the new version :)
