### ISSUE TITLE
Videos do not play on 5.0.5

### ISSUE THREAD

**Issue by ghomem** [rignaneseleo/SlimSocial-for-Facebook#133]
Seems that videos do not play on 5.0.5. We see this.

![WhatsApp Image 2021-06-14 at 12 37 39](https://user-images.githubusercontent.com/3352900/121886518-648a8280-cd0d-11eb-941d-f198742203b2.jpeg)

**Comment by ghomem** [comment]
Opened a separate issue for the videos:

https://github.com/rignaneseleo/SlimSocial-for-Facebook/issues/133

**Comment by essamadel** [comment]
I am having the same issue with v5.0.5. I have tried the apk and revert back to v5.0.4 when I experienced that video issue.

**Comment by rignaneseleo** [comment]
I don't think it is related with v5.0.5. I'm gonna dig into this ASAP.

**Comment by anishmittal2020** [comment]
Video can't be played in 5.0.5

**Comment by rignaneseleo** [comment]
Possibly solved in the new version. :)

**Comment by ghomem** [comment]
I confirmed this is solved on 5.0.8. Bravo @rignaneseleo !
