### ISSUE TITLE
'App not installed' when installing 5.0.7 on Android 11

### ISSUE THREAD

**Issue by Elbullazul** [rignaneseleo/SlimSocial-for-Facebook#136]
Opening the app icon shows the toast 'App not installed'. It can be opened through the app list in settings, but when uninstalling, it shows a warning: 'SlimSocial is a part of SlimSocial for Facebook'

I am using a Samsung A50 with Android 11 and OneUI 3

**Comment by fparri** [comment]
Same problem. App doesn't work here on Android 11 and Redmi Note 9s

**Comment by kowith337** [comment]
It seems like I can run this app once and not anymore, unless you've force stop and then relaunch app, and still can only launch app first time after force stop...

**Comment by geosphere** [comment]
Same issue on LOS 17.1 (Android 10)

**Comment by rignaneseleo** [comment]
Did you update from the Play Store?

**Comment by Elbullazul** [comment]
I installed the app from F-Droid

**Comment by ugurcansayan** [comment]
Same here. Updated via F-droid. In Launcher, it says app not found.

**Comment by AreYouLoco** [comment]
I also cannot launch an app after update to 5.0.7 it says "woops unable to launch that app" android 8.1 here.

**Comment by iamtalhaasghar** [comment]
I tried both methods:
1. installation from Fdroid
2. Downloading and installing apk directly from github releases.

None of the above works.
App version: 5.0.7

**Comment by erdnuesse** [comment]
Android 11, Pixel 4a 5G, security update 5/6/2021.
5.0.7 does not even start once for me. Shows a force closed dialogue for f-droid instead.
5.0.5 didn't work either, needed downgrade to 5.0.4

**Comment by bkw777** [comment]
Same here. Started at least a week ago. I don't know excatly the day it started but about a week maybe two. LineageOS 17.1 on a Pixel 4a 5g, installed from Fdroid. I tried uninstalling and rebooting and verifying that it's not installed from the Play Store and reinstalling from Fdroid.

It installs, and then when you try to launch, it just says "App not installed."

**Comment by anishmittal2020** [comment]
Unable to Install app on android 11

**Comment by rignaneseleo** [comment]
Solved in the new version. :)
