### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by linsui** [rignaneseleo/SlimSocial-for-Facebook#139]
In https://github.com/rignaneseleo/SlimSocial-for-Facebook/commit/ee9af80e501a817d14eec8985af0df4a6d6ad9cd com.android.billingclient is imported which is not FOSS. Could you please provide an FOSS flavor without that dependency? Thanks!

**Comment by hilburger** [comment]
That would be great because this makes your app a true alternative.
