### ISSUE TITLE
Current version not available in F-Droid

### ISSUE THREAD

**Issue by Krawei** [rignaneseleo/SlimSocial-for-Facebook#142]
Dear team,
when I take a look on google play store the current version is 5.0.4, in the F-Droid store the current version is 3.8.4.
What's the reason for this gap? Is there a bug in the build process?
Please fix this.
And thanks for your great work!

**Comment by hilburger** [comment]
Hi guys, 
I habe just discovered yout app after not using FB for a longer time. 
That's why I am also curious what the Problem with F-Droid is because I am running LineageOS without any Google Services and FOSS only. 
Thank you!

**Comment by miiichael** [comment]
Hmm, this bug is marked as completed, but F-Droid still only has a three year old version. :P
