### ISSUE TITLE
[Request] Cannot delete notifications

### ISSUE THREAD

**Issue by ElenaXX** [rignaneseleo/SlimSocial-for-Facebook#146]
It seems that there is no way to delete notifications as you do with the standard FB app or (even if in a more tedious way) with the web interface. I would be glad to see such a feature. In case there is a way to delete notifications instead but I could not find it I apologize in advance.

**Comment by 43367985** [comment]
wer bist du schlampe lg chani

Am Mo., 7. Feb. 2022 um 14:50 Uhr schrieb ElenaXX ***@***.***
