### ISSUE TITLE
No post show on feeds when turning on "Don't show sponsored posts"

### ISSUE THREAD

**Issue by trietphm** [rignaneseleo/SlimSocial-for-Facebook#147]
Hi,

It seems Facebook has a new update, right now if I turned on "Don't show sponsored posts", all the posts are filtered even if it's not a sponsored post.
The feeds is empty now with only "suggested for you", and only show posts (include sponsored posts) when disable "Dont show sponsored posts"

**Comment by Thanatoslayer6** [comment]
Couldn't agree more... its like redirecting twice if you enable that option hmm...

**Comment by trietphm** [comment]
I'm creating a PR #148 to fix this. If you trust me, you can download the APK file below and install it.

[SlimSocial.zip](https://github.com/rignaneseleo/SlimSocial-for-Facebook/files/8599179/SlimSocial.zip)
