### ISSUE TITLE
External links in the Messenger page cause white screen if I step back

### ISSUE THREAD

**Issue by andris155** [rignaneseleo/SlimSocial-for-Facebook#154]
When I open an external link from the received message in the SlimSocial messenger page and step back from the browser, the SlimSocial open a white blank page instead of messenger page.

App version: 5.0.8
Android version: 12L

**Comment by SteveParson** [comment]
@andris155  Did you try this on real hardware, or on an emulator?

**Comment by andris155** [comment]
I tested on real hardware.
