### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by A-7666** [rignaneseleo/SlimSocial-for-Facebook#156]
I always access FB via Tor, which is not possible on SlimSocial.
Please add the setting for custom proxy address.

**Comment by SteveParson** [comment]
@Agych  Could you add some context to this request? Are you only interested in being able to use Tor? What kind of proxy address would you like to be able to use?

**Comment by Agych** [comment]
Like in any other programs that have proxy settings (Bromite, FF, Signal, Forkgram for example),
to use any address/port set by the user

**Comment by GoFreeman** [comment]
Looking forward to seeing this feature too
Is there any chance for it to be added in the future?
