### ISSUE TITLE
Scrolling very laggy since flutter update 

### ISSUE THREAD

**Issue by rustyshakelford2** [rignaneseleo/SlimSocial-for-Facebook#166]
I noticed that scrolling through the feed is very laggy now after the new updates you have made. I downgraded to 5.0.8 and it is buttery smooth by comparison. This is on a OnePlus 9 pro with the 120hz display enabled. It feels like 30hz on the new version though. Need any more info?

**Comment by rignaneseleo** [comment]
I think the bug is caused by the webview that prints some logging. 
I disabled the logs in the v10.0.8, can you try it?

**Comment by rignaneseleo** [comment]
https://github.com/rignaneseleo/SlimSocial-for-Facebook/releases/tag/10.0.8%2B108

**Comment by axeleroy** [comment]
Just shimming in, the lags haven't improved with the latest version (10.0.9 from F-Droid on a Pixel 6 Pro running Android 13) and it feels even worse when locking the framerate to 60fps.

**Comment by rignaneseleo** [comment]
Do you have ads block turned on?

**Comment by axeleroy** [comment]
Yes, but turning it off doesn't seem to improve the responsiveness and framerate
