### ISSUE TITLE
Always reloading pages when clicking on top middle 

### ISSUE THREAD

**Issue by TomBonnot** [rignaneseleo/SlimSocial-for-Facebook#168]
As my title says, every time I click on the top half and center of my app, it says "reloading ..." and it refresh the page, so I can’t go trough Messenger or Marketplace or whatever. 

I am on a Pixel 7, using user agent : "Mozilla/5.0 (Linux; Android 11; SM-A507FN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Mobile Safari/537.36" (but with the main user agent it works too)

**Comment by rignaneseleo** [comment]
What's your app version?

**Comment by TomBonnot** [comment]
Tested both latest version (when I say "both" it's the one on Github and the one on FDroid)

**Comment by rignaneseleo** [comment]
Please check the version in the settings (at the bottom). 
It's really weird btw. I used to have a bugged scroll to refresh behavior but I took it out. 
When you tap on slimsocial text, it should go to the top of the page, without refreshing.



It would be useful a video of this bug.

**Comment by TomBonnot** [comment]
Did try the latest version and everything is fine. I don't know why it happened it was very weird, thanks for the fast answer and correction!
