### ISSUE TITLE
[Feature Request] Adding an option to use external app for links

### ISSUE THREAD

**Issue by TomBonnot** [rignaneseleo/SlimSocial-for-Facebook#169]
I think that for a more private app it is kind of required to redirect to the default apps or main browser. I could be really cool

But the app looks very nice for now!

**Comment by rignaneseleo** [comment]
You mean to open your browser app when an external link is tapped? 
I'm currently using https://pub.dev/packages/flutter_custom_tabs that opens a tab from your browser, directly in my app.
It's not an external browser, it's just the one that you are using, but partially executed over my app.

**Comment by TomBonnot** [comment]
Okay, I see it's the same thing as Feeder if I am not wrong.
I couldn't verify it so okay.
That's what I meant. So my feature request is not needed or a waste of time! Closing it, thank you for the informations!
