### ISSUE TITLE
Pictures and videos oversized/distorted in landscape mode

### ISSUE THREAD

**Issue by JSB2000** [rignaneseleo/SlimSocial-for-Facebook#173]
Thought that this problem was just occurring on my tablet due to how large the screen size is.  Then I tried landscape on my (smallish) phone and the same thing happens.  Videos and some pictures are so large/distorted that you can only see a portion of them and must scroll to see the rest.  Almost as if they are being resized to fit the total horizontal width of the device with no regard to the visible vertical height.

Switching to "Use basic version of Facebook" under settings restores functionality (pictures/videos are instead centered/reduced to the center of the screen with black filler on the left and right).  But, of course, this comes at the cost of most of the other benefits the app offers.

**Comment by rignaneseleo** [comment]
Hi, do you have a screenshot of this?

**Comment by JSB2000** [comment]
Sure.  Here's two screenshots of a representative video.  It's huge and too high to view.  So I have to decide whether to watch the top of the video:
![Screenshot_20230516_213302](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/8484306/91c80165-7689-401e-8acc-cd318d5fb064)

or the bottom:
![Screenshot_20230516_213324](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/8484306/71d0b896-759e-46f7-a0a9-b2a6c021c91f)

**Comment by rignaneseleo** [comment]
Oh I see, it' because you are using a tablet right? How about if you turn it in portrait mode? 
And how about if you press the full screen button?

**Comment by JSB2000** [comment]
Everything resizes properly in portrait mode. But in landscape mode, both on the tablet and on my phone, images and videos are both sized incorrectly.

**Comment by JSB2000** [comment]
3 weeks and nothing but crickets. Got it. Moving on...probably to Frost.
