### ISSUE TITLE
[BUG] Overlay issue on news feed

### ISSUE THREAD

**Issue by HarriBuh** [rignaneseleo/SlimSocial-for-Facebook#176]
![markup_1000010568](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/123186113/75009489-7258-408f-be9b-b973d67dea9b)

As one can see, the context menu is  always overlapping the corresponding post (which could be a regular thing), while being transparent at the same time, which is annoying.
This only happens with the dark design. Additionally, one can not spot the three dots icon.

Google Pixel 7
Android 13
SlimSocial version 10.0.9

**Comment by rignaneseleo** [comment]
Thanks for reporting!
