### ISSUE TITLE
5.0.5 cannot download images

### ISSUE THREAD

**Issue by jekv2** [rignaneseleo/SlimSocial-for-Facebook#178]
last working version, 5.0.5 cannot download images. cannot hold then save images, no way to save images.

**Comment by osowiecki** [comment]
You have to share the url and open it in firefox to save there.

**Comment by strider72** [comment]
> You have to share the url and open it in firefox to save there.

This requites you to log in on your main browser, which defeats much of the purpose of SlimSocial

**Comment by rignaneseleo** [comment]
Fixed on 10.1.0

**Comment by strider72** [comment]
I still can't download images
