### ISSUE TITLE
No option to disable video autoplay

### ISSUE THREAD

**Issue by vivia** [rignaneseleo/SlimSocial-for-Facebook#182]
Videos are now always autoplaying, and it's worse because of sponsored posts not being blocked: https://github.com/rignaneseleo/SlimSocial-for-Facebook/issues/181

I have to be careful about scrolling fast enough for videos to not finish loading, but it looks like they might still be playing in the background. Once I even accidentally unmuted a video while scrolling, and it started yelling after I had scrolled away from it.

If it's difficult to disable autoplay, could I at least get an option to disable videos entirely?

**Comment by NooB9496** [comment]
To disable autoplay of videos, click the three horizontal bars in the upper right corner under the "SlimSocial" bar. Go to settings, select autoplay videos and turn it off.

**Comment by calhix** [comment]
I was actually looking for this and I guess this setting was removed?

**Comment by calhix** [comment]
Actually, looks like it worked when going into your profile settings and searching for autoplay?
