### ISSUE TITLE
Is it abandoned again?

### ISSUE THREAD

**Issue by gothmog123** [rignaneseleo/SlimSocial-for-Facebook#201]
Sorry for whining

**Comment by squidds** [comment]
I don't believe you are whining. This is a great app. FB's FB app is just "code talk" for "give META all of your personal data". I too am curious if this app will see updates

**Comment by gothmog123** [comment]
> I don't believe you are whining. This is a great app. FB's FB app is just "code talk" for "give META all of your personal data". I too am curious if this app will see updates

thanks lol. yeah its such a great app it would be such a shame if it died

**Comment by rignaneseleo** [comment]
It's not died but as I wrote many times, this is just a side project among all the others. It's free and therefore I work on it only whenever I have spare time. Hope you understand :)
