### ISSUE TITLE
No longer accesses messenger messages

### ISSUE THREAD

**Issue by JosieDraus** [rignaneseleo/SlimSocial-for-Facebook#202]
CAN'T ENGAGE FACEBOOK MESSENGER IN THE NEW SLIM SOCIAL!!!!  In the previous versions, I could access both Facebook and Facebook messenger in one app.  Now I can't access messenger in either 10.0.9, or 10.0.8.  i finally got dark field working.  But can't access fb messenger at all without the official app.  All I get is a link to install the official fb messenger app! THIS IS DISTURBING!  Why can't I access fb messenger from SlimSocial anymore!

**Comment by diesel701** [comment]
I checked now and it's working on my device with the 10.0.9 version.

**Comment by gbakeman** [comment]
I am using version 10.0.9, and except for once a long time ago, Messenger/Messages has never worked for me on this app.

If I try to access Messenger by clicking on the button in the top bar, it looks like I'm presented with the desktop version of a login prompt. Logging in does not work:

![Screenshot_20240116-114531](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/842942/2136c58a-a4e6-4031-b88d-56d1254abf04)

If I try to access it by clicking on the Messenger button in the Facebook navigation bar up top, this is what I see:

![Screenshot_20240116-114540](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/842942/666e1c26-95c9-4d48-811b-7f15b3efd3c9)

And lastly, if I try to access Messenger by navigating to the hamburger menu in Facebook, then clicking on the Messenger link:

![Screenshot_20240116-114555](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/842942/a8b8637f-8102-485b-a65e-63bcc415e72c)

I'm not sure how it's working for anyone else, but it has been this way to me for a long time.

**Comment by lin0lin0** [comment]
@gbakeman 
be sure to use the correct Button - there are two.
I get the same "screenshot (Hangout ....)" if I tap the Messenger-Icon in the **white** top area, but if I tap the similar **BLUE** bar area messenger icon the messenger actually opens for me.

**Comment by lin0lin0** [comment]
@gbakeman not sure about geo location (I'm in Germany) but your ScreenShot batches mine (except having white instead of dark mode).
Button "2" gives me the "login message" (1st picture of your 1st post) - button "1" is working for me in one android9 Phone as well as in an Android13 Phone.
Next to your Button "1" the three dot menu --> in settings I did activate (in German highest toggle) switched to ACTIVATE MESSENGER; did you miss to active it in your settings?

**Comment by gbakeman** [comment]
I did not think to check my settings! I just checked after your message, and it turns out I did have Messenger enabled. I tried toggling the setting on and off just in case, unfortunately the issues persist. thank you for the ideas.

**Comment by diesel701** [comment]
What is the error message you get when you try to login to messenger?

**Comment by gbakeman** [comment]
> What is the error message you get when you try to login to messenger?

Last time I tried logging in, I remember it either redirecting back to the login page or to the main facebook page. But this time, it did give me access to my messages! Of course the other avenues for accessing Messenger still have the same result, but at least the SlimSocial button seems to work. Thank you for the suggestion!

**Comment by rignaneseleo** [comment]
Hey guys, I think the error is related to the location and the user agent. There's not much I can do, unless one of you tells me the user agent that makes it work in your location (you can try custom UA it in the settings).

**Comment by rignaneseleo** [comment]
> btw. could you add a toggle for Language? My Android UI is in German, and I am not to happy to change the UI in general to English to find the original description texts :-)

If you are on the latest version of Android, you should be able to set a custom language from the OS app settings.
