### ISSUE TITLE
Feedback on Recent Size Increase of Slim Social for Facebook

### ISSUE THREAD

**Issue by kamrulhasanio** [rignaneseleo/SlimSocial-for-Facebook#204]
Dear @rignaneseleo ,

I hope this message finds you well. I wanted to take a moment to share some feedback regarding the recent development of Slim Social for Facebook.

Firstly, I want to express my appreciation for your efforts in creating and maintaining Slim Social. It has been my go-to app for accessing Facebook due to its lightweight nature, providing a streamlined experience without compromising functionality.

However, I have noticed a significant increase in the app's size since it underwent development using Flutter. From being less than half a MB, it has now ballooned to over 20MB. This shift is concerning to me, as one of the main reasons I favored Slim Social was its small footprint on my device.

Considering that the official lite version of Facebook weighs in at only 2MB and is a native app, I believe there is an opportunity to optimize Slim Social to maintain its lightweight appeal. While I understand the benefits and features Flutter brings to the table, I urge you to explore avenues to minimize the app's size while preserving its functionality.

Maintaining Slim Social as a lightweight alternative to the official Facebook app is crucial for users like myself who value efficiency and minimalism. I trust in your expertise and dedication to address this concern, and I look forward to seeing Slim Social continue to thrive as a lightweight option for accessing Facebook.

Thank you for considering my feedback.

Best regards,
Kamrul Hasan

**Comment by rignaneseleo** [comment]
Dear Kamrul,

Thank you for your valuable feedback and for your continued support of Slim Social for Facebook. I understand your concerns about the increase in the app’s size.

The shift to Flutter was a decision I made to improve the development speed and the overall user experience. While this has led to an increase in the app’s size, it has also allowed me to introduce new features and improvements more quickly.

In terms of the app’s size, it’s important to note that the storage capacities of devices have significantly increased over the years. In 2024, a 20MB app is relatively smaller in proportion to the total storage space available on most devices, compared to 10 years ago. Therefore, while the absolute size of the app has increased, its relative impact on your device’s storage has not.

That being said, I am continuously working on optimizing the app and am exploring ways to reduce its size without compromising on functionality. Your feedback is crucial in this process and I appreciate your understanding and patience as I strive to make Slim Social the best it can be.

Thank you once again for your feedback.
