### ISSUE TITLE
Slim don't remove adds

### ISSUE THREAD

**Issue by PrzemekSkw** [rignaneseleo/SlimSocial-for-Facebook#208]
Hello, I install today from F-droid and I see that it don't remove adds. Can I do something with that?
![Screenshot_2024-04-10-13-39-44-67_18acbe38108a01532324fb2d596236d6](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/25219988/679965f2-6dd8-4af0-af7b-41caf172220e)

![Screenshot_2024-04-10-13-40-47-87_18acbe38108a01532324fb2d596236d6](https://github.com/rignaneseleo/SlimSocial-for-Facebook/assets/25219988/f45e98f5-44e6-4344-a049-c5af6de79b6f)

Regards.

**Comment by rignaneseleo** [comment]
Facebook ads posts are always change shape to avoid adblockers. Let's see if I can find some new method.

**Comment by jumpingbrowntrout** [comment]
@rignaneseleo Same as my comment here, this greasemonkey script works very well. 
https://github.com/rignaneseleo/SlimSocial-for-Facebook/issues/195#issuecomment-2817294504
