### ISSUE TITLE
"Show all notifications" link won't appear

### ISSUE THREAD

**Issue by Jadelor** [rignaneseleo/SlimSocial-for-Facebook#21]
The "show all notifications" link that appears after the latest notifications when you tap the "earth" button in the Facebook top bar won't show on SlimSocial. It shows up on FaceSlim and m.facebook.com.

**Comment by rignaneseleo** [comment]
I'm working about it. Actually you could set the text size smaller to show more notifications :)

**Comment by Jadelor** [comment]
Yes! I did it the moment the text size toggle appeared!

**Comment by rignaneseleo** [comment]
From the v.3.0 it is always shown! :)
