### ISSUE TITLE
Problem with opening messages

### ISSUE THREAD

**Issue by CharlesPL** [rignaneseleo/SlimSocial-for-Facebook#26]
The Facebook introduced the message on their site that in feature messaging will be only available via messenger. This warning is shown everytime I visit messages. Could you fix it and block that element?

**Comment by rignaneseleo** [comment]
Hi Charles! 
In the alpha version (soon available as beta) I'm adding the possibility to open Messanger.com :)

**Comment by rignaneseleo** [comment]
With the v3.5 I implemented messages :)
