### ISSUE TITLE
Randomly switches options when scrolling in settings

### ISSUE THREAD

**Issue by kinclma1** [rignaneseleo/SlimSocial-for-Facebook#29]
Version 3.0.0 from Google Play on Huawei Y300 (Android 4.1.1):

In the settings activity, random options turn on when I scroll down. For the most time currently, it's the "Fixed top bar" option switching on.

**Comment by rignaneseleo** [comment]
Thanks for telling me this issue.
Also with the v3.5? https://github.com/rignaneseleo/SlimSocial-for-Facebook/releases/download/v3.5.0/SlimSocial.for.Facebook.3.5.0.apk

**Comment by kinclma1** [comment]
This one also without change.

**Comment by kinclma1** [comment]
Now it seems to have gotten much worse, switching multiple switches on and of at the same time.

**Comment by rignaneseleo** [comment]
can you post a settings  screenshot?

**Comment by kinclma1** [comment]
![screenshot_2016-06-10-23-06-14](https://cloud.githubusercontent.com/assets/2377824/15978717/440b9d3c-2f60-11e6-98dc-f18c86498f4f.png)
![screenshot_2016-06-10-23-06-22](https://cloud.githubusercontent.com/assets/2377824/15978718/440fc704-2f60-11e6-829b-b5174ee5272c.png)

**Comment by rignaneseleo** [comment]
Thanks. There are some bugs with Android 4.1.1. With the version before the 3.0 did you have this issue?

**Comment by kinclma1** [comment]
I think that it was there from the start.

**Comment by rignaneseleo** [comment]
I've read this http://stackoverflow.com/questions/15632215/preference-items-being-automatically-re-set

Try with this APK:
[app-release.zip](https://github.com/rignaneseleo/SlimSocial-for-Facebook/files/309796/app-release.zip)

**Comment by kinclma1** [comment]
Seems to work fine, thank you.

**Comment by kinclma1** [comment]
It has also fixed https://github.com/rignaneseleo/SlimSocial-for-Facebook/issues/30

**Comment by rignaneseleo** [comment]
I fixed this and #30 issues in the v3.5.1 :8ball:
