### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by betsythefc** [rignaneseleo/SlimSocial-for-Facebook#33]
Hello!

I don't use SlimSocial yet but I'd like to.
Can it be added to the F-Droid app store for Open Source apps?

https://f-droid.org/contribute/

**Comment by rignaneseleo** [comment]
Haven't you got the Play Store? I prefer have all users in the same platform to study the analytics data and read the comments more simply.

**Comment by betsythefc** [comment]
I do have the play store, but I am in the process of getting rid of it to rely solely on F-droid.

**Comment by kolya-ay** [comment]
@betsythefc It seems [it has been done](https://f-droid.org/repository/browse/?fdfilter=facebook&fdid=it.rignanese.leo.slimfacebook).

**Comment by betsythefc** [comment]
@kolya-ay Thanks for the heads up!
