### ISSUE TITLE
No internet connection message

### ISSUE THREAD

**Issue by Eva850** [rignaneseleo/SlimSocial-for-Facebook#34]
Hello, I have a problem with your app. Since a week a "No internet connection" notification appears, although I have connection. Main page also opens fine. It appears when I try to open message or group. I tried to clear app data, but no luck. Screenshot of message: https://drive.google.com/file/d/0B6g6Av7dwyPFX2NTdlpoWmdWZjA/view?usp=drivesdk

**Comment by rignaneseleo** [comment]
If you switch from 3g to wifi or vice versa it still doesn't work?

**Comment by Eva850** [comment]
Yes, problem persists.  This is a video which explains what happens:
https://drive.google.com/file/d/0B6g6Av7dwyPFblVKcWJKRVFURTA/view?usp=drivesdk

**Comment by rignaneseleo** [comment]
it is pretty strange! Now I'll check some things, thank you

**Comment by Eva850** [comment]
I checked your app on other device and this error also appears. Maybe facebook changed something since last week.

**Comment by kwiateusz** [comment]
I got it too, on 2 devices. Bug is only present on 3/4g, on wifi is ok.

**Comment by Eva850** [comment]
I got it on WiFi and 3g on two different devices and two different accounts. I switched to Swipe. There is also the same bug, but it happens less often, so I could use it normally.

**Comment by rignaneseleo** [comment]
what is the last version working on your devices?

**Comment by Eva850** [comment]
Where I can download older versions to test? I use version 3.6.2 and this issue is there

**Comment by rignaneseleo** [comment]
Here https://github.com/rignaneseleo/SlimSocial-for-Facebook/releases
The version 2.2.4 should work
