### ISSUE TITLE
Facebook over tor

### ISSUE THREAD

**Issue by Mher594** [rignaneseleo/SlimSocial-for-Facebook#35]
It would be great to have orbot support in setting.

**Comment by m-boyd** [comment]
Seconded. Not just operating over Tor but using [facebookcorewwwi.onion](https://www.facebookcorewwwi.onion) as well.

**Comment by Adrianzo** [comment]
I'm using the other app on fdroid, face slim, because of this. It's curious... because slimsocial for twitter appears to be proxyable with orbot.
