### ISSUE TITLE
WebView 55 Breaks SlimSocial

### ISSUE THREAD

**Issue by craig-st** [rignaneseleo/SlimSocial-for-Facebook#36]
Upgrading Android System WebView from version 52 to version 55 causes  SlimSocial 3.5.6 to show only a blank, white screen. (FaceSlim also exhibits the same behavior after the WebView upgrade). Android 5.1.1 Validus ROM

**Comment by lollox** [comment]
On my MotoG 3gen the last updates (WebView 55 and last SlimSocial) give me the desktop version of FB

**Comment by craig-st** [comment]
I updated the webview through the Play store.  SlimSocial through f-droid.

**Comment by lollox** [comment]
I use the PlayStore for alla my software

**Comment by rignaneseleo** [comment]
I haven't any issue with the last WebView version. You should try the version 3.6.2 :)

**Comment by lollox** [comment]
I've already the 3.6.2

**Comment by craig-st** [comment]
3.6.2 hasn't fixed the problem for me.  Same behavior.  Blank, white
screen.  With Android System Webview 55.0.2883.91
(com.google.android.webview)

**Comment by rignaneseleo** [comment]
Try the [version 2.2.4](https://github.com/rignaneseleo/SlimSocial-for-Facebook/releases/download/v2.2.4/SlimSocial.for.Facebook.v2.2.4.apk) (before the implementation of AdvancedWebView)
