### ISSUE TITLE
Continue video when minimized

### ISSUE THREAD

**Issue by PanderMusubi** [rignaneseleo/SlimSocial-for-Facebook#39]
Please, continue playing a video on Facebook when the app is minimized.

**Comment by PanderMusubi** [comment]
Or when the screen is locked

**Comment by rignaneseleo** [comment]
I think is not possible because the entire app goes in 'stand-by' when the screen is off (like Youtube).

**Comment by PanderMusubi** [comment]
https://www.f-droid.org/packages/org.schabi.newpipe/ can do it
