### ISSUE TITLE
Stucked in "Show picture in full size"

### ISSUE THREAD

**Issue by xavihernandez** [rignaneseleo/SlimSocial-for-Facebook#43]
Most of the time, when I hit "show picture in full size" I am not able to go back. Then I'm stucked on this picture in full size, and I'm oblige to hit "Home" (of Facebook) or something like that to continue. I cannot just go back with "back" button of Android.

**Comment by rignaneseleo** [comment]
I fixed it in the v3.7.0 :)

**Comment by xavihernandez** [comment]
Ok thank you
