### ISSUE TITLE
Dark Theme Needs Some Tweaking... 

### ISSUE THREAD

**Issue by ibuprophen1** [rignaneseleo/SlimSocial-for-Facebook#44]
I have a suggestion to help with a small (and a little annoying) yet tolerable issue regarding the Dark Theme of the app.

The Dark Theme of the app does work but, when areas have a more darker shade of color (like a darker gray, blue, red, etc...), it is a bit challenging to see those other colors on top of the black background.

It would be GREAT if there was something to help with those darker colors like a color chooser or another way on helping out this Dark Theme become a bit more Visually acceptable to the eyes without being forced to temporarily turn up the devices brightness when using this app.

Thank you!

**Comment by rignaneseleo** [comment]
I fixed the most of the bugs in the v3.7.1 👍
