### ISSUE TITLE
Paypal link shows italian error message

### ISSUE THREAD

**Issue by burakozhan** [rignaneseleo/SlimSocial-for-Facebook#45]
I tried to donate something via the paypal link in the github readme. Unfortunately I was forwarded to some italian language error message. Please change language, and fix error.

**Comment by rignaneseleo** [comment]
Thank you for the reporting!
The link to donate should be: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7NFPYFBNAL3AL
Does it work? Can you send me the italian error?

**Comment by burakozhan** [comment]
The new link in the comment above works.

The following was the error message if I click on the Link from the README.md file:

Spiacenti - impossibile completare l'ultima azione

Se stavi effettuando un acquisto o inviando un pagamento, ti consigliamo di controllare sia il tuo conto PayPal che la tua email per la conferma della transazione nei 30 minuti successivi. Se esegui nuovamente l'azione in questo momento, potrebbe verificarsi un pagamento doppio.

Se non stavi effettuando un pagamento o inviando denaro e ti trovavi su un altro sito web, torna su quel sito (non utilizzare il pulsante Indietro del browser) ed esegui nuovamente l'azione.

Se ti trovavi nel sito web di PayPal, clicca il logo PayPal nell'angolo superiore sinistro per tornare alla home page ed eseguire nuovamente l'azione. È possibile che tu debba eseguire nuovamente l'accesso.

**Comment by rignaneseleo** [comment]
Link updated, thanks! 👍
