### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [rignaneseleo/SlimSocial-for-Facebook#48]
Hi @rignaneseleo 

I found [this app](https://play.google.com/store/apps/details?id=com.republic.fb) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Add a link to this repo, and another one to the original app.

**Comment by Poussinou** [comment]
@rignaneseleo There is also [this one](https://play.google.com/store/apps/details?id=com.dev.alshikh.fbsocial) !

**Comment by ibuprophen1** [comment]
I just submitted an Objection Complaint on the Play Store for both those apps. 

I stated the following:

"This app was taken and slightly changed from an app already on the Play Store "https://play.google.com/store/apps/details?id=it.rignanese.leo.slimfacebook". 

Isn't this considered a Copyright Violation? 

Thank you very much for your time and understanding."

Why not do the same for those apps?

**Comment by Poussinou** [comment]
What is the URL you used to submit this complain? You want me to do the same?

**Comment by ibuprophen1** [comment]
In the Play Store, go to one of the apps in question, scroll down to the bottom and select the "Flag as inappropriate", on the next screen select the "Other" and select the

**Comment by rignaneseleo** [comment]
Thanks guys. I did it.
Keep reporting these type of apps. 👍

**Comment by knezi** [comment]
The app from the first link is still available in Google Play store and I haven't found any link to the original app. Did the DMCA takedown  not succeed?

**Comment by rignaneseleo** [comment]
Here you go https://play.google.com/store/apps/details?id=it.rignanese.leo.slimfacebook

**Comment by knezi** [comment]
I was referring to the licence violating app, as it is still in the playstore.
