### ISSUE TITLE
Even larger font

### ISSUE THREAD

**Issue by ChristianTacke** [rignaneseleo/SlimSocial-for-Facebook#49]
I love the option to change the font sizes. But even the "Huge" setting yields nearly readable font sizes. Could you add an "Extra Huge" setting, please? Or make the difference between the settings larger, so that using "Huge" gives larger fonts?

**Comment by rignaneseleo** [comment]
I added the extra-huge font in the v3.7.1 :)

**Comment by ChristianTacke** [comment]
That's already a lot better!
