### ISSUE TITLE
Application crashes when the "Open in the browser" button is clicked with the phone's data connection turned off

### ISSUE THREAD

**Issue by codaphrenic** [rignaneseleo/SlimSocial-for-Facebook#57]
#### Expected behavior
I expect the application to show a message prompt that reads "data connection turned off" or rather, it should open the selected browser, then a message in the browser notifies you of the turned off data connection.

Opening the page in the browser should be a function that is set in motion when the intended browser opens, such that the error of not having the data turned on would be displayed as a message by the browser when it opens. And not the application crashing before the browser even opens.

#### Actual behavior

The application crashes when the "open in the browser" button is clicked with the phone's data connection turned off.

#### How to reproduce
* download the app from fdroid store
* Turn off data connections
* launch app and allow permissions if prompted
* Click on the three dots at the top right corner of the display and the app crashes. However, the dialog box that allows for the selection of a browser pops up when the data connection is turned on.

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: SlimSocial
* version: 3.7.1

#### Recording Of The Bug

<sub>
<center>
The recording below shows the button worked as it supposed to but crashed when the data connection is turned off before clicking. 
</center>
</sub>
<center>
https://youtu.be/X6pJXvR8MBs
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/application-crashes-when-the-open-in-browser-button-is-clicked-with-the-phone-s-data-connection-turned-off">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by rignaneseleo** [comment]
Fixed!
