### ISSUE TITLE
Unable to scroll up the menu page after scrolling down, the page refreshes instead

### ISSUE THREAD

**Issue by codaphrenic** [rignaneseleo/SlimSocial-for-Facebook#59]
#### Expected behavior
I expect i'll be able to scroll down and then back up the menu page without experiencing any hitch.

#### Actual behavior

I am unable to scroll back up after scrolling down. Instead, when i try to scroll up, the page tries to refresh itself. It likes my thumb motions are directed at scrolling up, while the page seems bent on refreshing.

#### How to reproduce
* download the app from fdroid store
* launch app and allow permissions if prompted
* Turn on data connections
* Login with your facebook details
* Refresh the homepage
* Click on the three slashes just below the three dots at the top right corner.
* Attempt scrolling down
* Now try scrolling back up, you'll notice the page refreshes instead

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: SlimSocial
* version: 3.7.1

#### Recording Of The Bug
<sub>
<center>
The video shows it scrolls properly on the homepage but on the menu page one can only scroll down but not up.
</center>
</sub>

<center>
https://youtu.be/nmHT9EEAIDI
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/unable-to-scroll-up-the-menu-page-after-scrolling-down-the-page-refreshes-instead">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by rredford** [comment]
Also affects version 3.8.4

**Comment by rredford** [comment]
Was it fixed?

**Comment by rignaneseleo** [comment]
I closed it due to the old date. I cleaned the issues list. If still ongoing, please open a new one.
Thanks

**Comment by rredford** [comment]
Ok will do.
