### ISSUE TITLE
Bug on Slimsocial for facebbok.: App refuse to log users in through the app

### ISSUE THREAD

**Issue by idimummy** [rignaneseleo/SlimSocial-for-Facebook#60]
#### Expected behavior
The app should allow users to login through the app NOT through the web browser.

#### Actual behavior
Logging in through the app loads endlessly without a response

#### How to reproduce
• Download slimsocial for facebook from play store here, 
• launch the app, 
• click to enter your login details (phone number or email), 
• click on login. It loads endlessly 
• Alternatively, select the option menu to login through the browser

* Operating system: Android Version 7.0
*Device used: Tecno Boom J8 
* App Version: 3.7.1

#### Recording Of The Bug
https://youtu.be/48THcL7rJaU
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kennykajo/bug-on-slimsocial-for-facebbok-app-refuse-to-log-users-in-through-the-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by SteveParson** [comment]
@idimummy , can you check to see if this is still a problem? When I tested this behavior, I was not able to reproduce a login screen that did not have a password field. Maybe Fakebook has updated their mobile page?
