### ISSUE TITLE
[Bug] Facebook menu not shown correctly

### ISSUE THREAD

**Issue by github-throwaway** [rignaneseleo/SlimSocial-for-Facebook#63]
The menu is not shown correctly as seen in the screenshot:

![20180416_121129](https://user-images.githubusercontent.com/25488086/38880019-fa4171c6-4264-11e8-865d-568e707311f5.png)

**N9005 | Android 5.0 | SlimSocial for Facebook 3.7.1**

**Comment by rignaneseleo** [comment]
It's the first time I see this. Do you still have it?
