### ISSUE TITLE
Videos do not play.

### ISSUE THREAD

**Issue by j-ep** [rignaneseleo/SlimSocial-for-Facebook#66]
When attempting to play a Facebook video, a small video frame appears, but the page is otherwise unresponsive and the video does not play.

**Comment by stevep1983** [comment]
![image](https://user-images.githubusercontent.com/20347119/39961732-eb83788e-55f9-11e8-9023-9bd0e96bdd97.png)

This doesn't happen with every video for me. I can save the video using the icon on the upper right. It savves as SlimSocial.jpg

Confirmed with:
Android emulator (Android 5.1.1)
Lenovo A1000 (Android 5.0)
LG H812 (aka G4)  (Android 6)
