### ISSUE TITLE
mbasic new messages

### ISSUE THREAD

**Issue by dannycolin** [rignaneseleo/SlimSocial-for-Facebook#67]
Since mbasic doesn't refresh a conversation (thread) a good workaround could be to force refreshing the page every X seconds or minutes. @rignaneseleo What do you think about that?

**Comment by rignaneseleo** [comment]
This is not a bad idea but there are some problems to handle. 
One that came now in my mind is when you are scolling your messages to read an old one: if it refreshes every 20 seconds, you won't be able to do that.

**Comment by dannycolin** [comment]
> One that came now in my mind is when you are scolling your messages to read an old one: if it refreshes every 20 seconds, you won't be able to do that.

Would it be possible (like browser extensions) to inject a JS script in the page and detect if a user scrollback?

**Comment by stevep1983** [comment]
@dannycolin I'm interested in your idea of injecting a JS script, but I'm not entirely sure what you mean. Can you clarify it further?

**Comment by dannycolin** [comment]
@stevep1983 sorry for the late response. 

I meant that we can use the same technique that @rignaneseleo use with the Dark theme. He loaded a custom CSS file that change the colors of the FB page.

**Comment by stevep1983** [comment]
Thanks for your reply. I am missing something with respect to your
proposal. Do you mean live updates of a thread that is receiving messages
as you are viewing it?

**Comment by dannycolin** [comment]
> Do you mean live updates of a thread that is receiving messages as you are viewing it?

Yes. My proposal was to refresh the thread automatically instead of using the refresh button.

**Comment by rignaneseleo** [comment]
Since messages are still working in the touch.facebook.com domain, your idea is not necessary now. Maybe in the future! :)

**Comment by dannycolin** [comment]
Wasn't aware of touch.facebook.com. Thanks for the link. Does it auto-refresh when you receive a msg?
