### ISSUE TITLE
Feature request ; option to disable media loading over wifi

### ISSUE THREAD

**Issue by rpdelaney** [rignaneseleo/SlimSocial-for-Facebook#76]
Pretty much the subject. I can't use this app on mobile because I have limited mobile data, and switching back and forth in the setting is annoying.

**Comment by WPFilmmaker** [comment]
Maybe a 'tap to view' option would allow a more granular experience?One could view only the media he wants. Whatsapp does something like that if you dig into options-

**Comment by iriseecz** [comment]
Or add to settings (like in Firefox): Images / Videos etc. -> Always, Only over Wi-Fi, Blocked.
