### ISSUE TITLE
sharing error: href should represent a valid URL

### ISSUE THREAD

**Issue by HacimLlih** [rignaneseleo/SlimSocial-for-Facebook#77]
When attempting to share a Google news article, slim social always displays a red error notification and fails that reads:

"href should represent a valid URL"

Screenshot:
https://photos.app.goo.gl/Myz4jtYySibk1ndq7

**Comment by rignaneseleo** [comment]
I think it is caused by the SharedWithSlimSocial attached at the end of the url. 
I removed it in the v3.7.5 :)
