### ISSUE TITLE
Remove FBCLID from links

### ISSUE THREAD

**Issue by bwstefano** [rignaneseleo/SlimSocial-for-Facebook#83]
About three months ago Facebook implemented a feature called FBCLID. There's no official documentation to it but it adds this FBCLID parameter to the end of each URL shared on Facebook, supposedly working the same way as GCLID (Google Click Identifier). It would be interesting if SlimSocial removed these from links clicked inside the app.

**Comment by toastal** [comment]
ala https://addons.mozilla.org/en-US/firefox/addon/utm-tracking-token-stripper/

**Comment by AreYouLoco** [comment]
Vote +1
I did a PR for one of the FF addons doing that. But I guess SlimSocial is using webview so yes @toastal a chrome addon integrated should do fine.
