### ISSUE TITLE
Hide: Stories and People you may know

### ISSUE THREAD

**Issue by anishmittal2020** [rignaneseleo/SlimSocial-for-Facebook#99]
Is it possible to hide  "Stories" and "People you may know"? They take the whole screen space! Or may be have an option for those who want to hide it.

![Screenshot_20200630-081636_SlimSocial for Facebook](https://user-images.githubusercontent.com/42092626/86090323-28352680-baaa-11ea-8bd1-37e93c18094d.png)

**Comment by rredford** [comment]
Please. :) I want this too.
